# Generated by Django 3.1.3 on 2022-01-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_uploadfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
        migrations.AlterField(
            model_name='review',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
    ]
