# Generated by Django 2.2.5 on 2022-01-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_remove_course_cnt_alter_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('type', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'army_shop',
                'ordering': ['-id', 'year', 'month', 'type', 'name'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
