# Generated by Django 2.2.5 on 2022-01-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_auto_20220119_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cnt',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
